# Generated by Django 5.1.15 on 2026-05-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP — Fuel & Procurement'), ('utility_electricity', 'Utility — Electricity'), ('travel_concur', 'Corporate Travel')], max_length=32)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('parser_notes', models.JSONField(blank=True, default=dict)),
                ('row_count_raw', models.PositiveIntegerField(default=0)),
                ('row_count_normalized', models.PositiveIntegerField(default=0)),
                ('row_count_failed', models.PositiveIntegerField(default=0)),
                ('row_count_flagged', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.analystuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('parse_error', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.organization')),
            ],
            options={
                'ordering': ['batch_id', 'source_row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', '-created_at'], name='ingestion_i_organiz_e16591_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'file_sha256'], name='ingestion_i_organiz_6bd012_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'batch', 'source_row_number'], name='ingestion_r_organiz_016497_idx'),
        ),
    ]
