# Generated by Django 5.1.15 on 2026-05-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCodeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('diesel', 'Diesel fuel'), ('petrol', 'Petrol / Gasoline'), ('natural_gas', 'Natural gas'), ('lpg', 'LPG'), ('electricity', 'Grid electricity'), ('flight_short', 'Flight — short haul'), ('flight_medium', 'Flight — medium haul'), ('flight_long', 'Flight — long haul'), ('hotel_night', 'Hotel — per night'), ('taxi', 'Taxi / ride-hail'), ('rail', 'Rail'), ('other', 'Other / unmapped')], max_length=32)),
                ('unit', models.CharField(choices=[('L', 'litre'), ('kg', 'kilogram'), ('kWh', 'kilowatt-hour'), ('pkm', 'passenger-kilometre'), ('night', 'room-night'), ('km', 'kilometre')], max_length=16)),
                ('region', models.CharField(help_text="ISO country code or 'GLOBAL'", max_length=8)),
                ('valid_year', models.PositiveSmallIntegerField()),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(help_text='DEFRA 2024, India CEA v19, ICAO 2023, etc.', max_length=120)),
            ],
            options={
                'indexes': [models.Index(fields=['activity_type', 'region', 'valid_year'], name='emissions_e_activit_b1534b_idx')],
                'unique_together': {('activity_type', 'unit', 'region', 'valid_year')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct'), ('scope_2', 'Scope 2 — Purchased energy'), ('scope_3', 'Scope 3 — Value chain')], max_length=16)),
                ('activity_type', models.CharField(choices=[('diesel', 'Diesel fuel'), ('petrol', 'Petrol / Gasoline'), ('natural_gas', 'Natural gas'), ('lpg', 'LPG'), ('electricity', 'Grid electricity'), ('flight_short', 'Flight — short haul'), ('flight_medium', 'Flight — medium haul'), ('flight_long', 'Flight — long haul'), ('hotel_night', 'Hotel — per night'), ('taxi', 'Taxi / ride-hail'), ('rail', 'Rail'), ('other', 'Other / unmapped')], max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=32)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(choices=[('L', 'litre'), ('kg', 'kilogram'), ('kWh', 'kilowatt-hour'), ('pkm', 'passenger-kilometre'), ('night', 'room-night'), ('km', 'kilometre')], max_length=16)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('flagged', 'Flagged — needs analyst attention'), ('approved', 'Approved (locked)'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('edited_after_import', models.BooleanField(default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.analystuser')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.ingestionbatch')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.analystuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_record', to='ingestion.rawrecord')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlantCodeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_code', models.CharField(max_length=8)),
                ('site_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('ingested', 'Ingested'), ('flagged', 'Flagged by validator'), ('edited', 'Edited by analyst'), ('approved', 'Approved (locked)'), ('rejected', 'Rejected')], max_length=16)),
                ('actor_label', models.CharField(default='system', max_length=200)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='emissions.activityrecord')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.analystuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='emissions_a_organiz_ee5338_idx'), models.Index(fields=['activity_record', '-created_at'], name='emissions_a_activit_3f3b57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'status', 'scope'], name='emissions_a_organiz_d3e905_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'period_start'], name='emissions_a_organiz_26f12c_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['batch', 'status'], name='emissions_a_batch_i_ee8ae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantcodemap',
            unique_together={('organization', 'plant_code')},
        ),
    ]
